service: prototype-express-lambda 
provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${opt:stage}

functions:
  express:
    handler: src/handler.express
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
