service: prototype-typescript-plugin

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
